#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

yarn lint ||
(
    echo '🤢🤮🤢🤮 Its F**KING RAW - Your styling looks disgusting. 🤢🤮🤢🤮
            Prettier Check Failed. Run npm run format, add changes and try commit again.';
    false;
)

echo '🤔🤔🤔🤔... Alright... Code looks good to me...🤔🤔🤔🤔'

echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'
